import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
// Bundle the TypeScript modules for Node; these tests concern UI boundaries only.
async function moduleFor(entry){const r=await build({entryPoints:[entry],bundle:true,write:false,format:'esm',platform:'node'});return import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'));}
const {createFixtureBridge,shortageSeconds}=await moduleFor('src/fixture.ts');
const {parsePreferences,DEFAULTS}=await moduleFor('src/preferences.ts');
const {roles,structures}=await moduleFor('src/catalog.ts');
test('React snapshot is cached until changed and deeply read-only for exposed arrays',()=>{const b=createFixtureBridge();const s=b.getSnapshot();assert.equal(s,b.getSnapshot());assert.throws(()=>{s.resources[0].amount=0});assert.throws(()=>s.intents.push('edit'));b.dispatch({type:'select',role:'Ping'});assert.notEqual(s,b.getSnapshot());assert.equal(s.selected,'Bulwark');});
test('unsubscribe prevents stale React listeners after unmount',()=>{const b=createFixtureBridge();let n=0;const stop=b.subscribe(()=>n++);b.dispatch({type:'pause-scene'});stop();b.dispatch({type:'pause-scene'});assert.equal(n,1);});
test('preview commands never alter resource balances or represent accepted engine orders',()=>{const b=createFixtureBridge();const before=structuredClone(b.getSnapshot().resources);for(let i=0;i<20;i++)b.dispatch({type:'preview-order',order:'Fork'});assert.deepEqual(b.getSnapshot().resources,before);assert.equal(b.getSnapshot().intents.length,5);assert.match(b.getSnapshot().intents[0],/no game command sent/);});
test('all critical sample states can be entered and recovered by switching fixture',()=>{const b=createFixtureBridge();for(const scenario of ['code-low','brownout','suspended','stable']){b.dispatch({type:'scenario',scenario});assert.equal(b.getSnapshot().scenario,scenario);}assert.equal(b.getSnapshot().suspended,0);});
test('shortage estimates handle positive, zero and invalid rates without NaN warnings',()=>{assert.equal(shortageSeconds(80,-4),20);assert.equal(shortageSeconds(80,0),null);assert.equal(shortageSeconds(80,4),null);assert.equal(shortageSeconds(0,-4),0);assert.equal(shortageSeconds(-1,-4),null);assert.equal(shortageSeconds(Infinity,-4),null);});
test('untrusted or old preference schemas reset and out-of-range inputs clamp',()=>{assert.deepEqual(parsePreferences(null),DEFAULTS);assert.deepEqual(parsePreferences({schema:4,scale:400}),DEFAULTS);const p=parsePreferences({schema:1,scale:900,reducedMotion:'false',shapes:false,pauseKey:'KeyQ'});assert.equal(p.scale,125);assert.equal(p.reducedMotion,false);assert.equal(p.shapes,false);assert.equal(p.pauseKey,'Space');assert.equal(parsePreferences({schema:1,scale:NaN}).scale,100);});
test('presentation catalog matches the supplied six roles and ten buildings exactly',()=>{assert.deepEqual(roles.map(r=>r.name),['Runner','Ping','Bulwark','Lancer','Patcher','Breaker']);assert.deepEqual(structures.map(s=>s.name),['Core','Data Cache','Compiler','Mining Rig','Compute Node','Memory Bank','Training Grid','Firewall','Access Gate','Sentry Tower']);});
