// Economy simulation: runs the real simulation headless with scripted economic personalities
// (no combat) and records time series. Balance evidence only — not proof of fun.
// Usage: npm run econ   → writes docs/ECON_SIM_RESULTS.md and docs/econ_sim.json
import { writeFileSync, mkdirSync } from 'node:fs';
import { Game } from '../src/sim/game.ts';
import { AIController } from '../src/sim/ai.ts';
import { B } from '../src/sim/types.ts';
import { codeIncomeRate } from '../src/sim/systems.ts';
import { completeBuilding } from '../src/sim/systems.ts';

interface Scenario { id: string; title: string; question: string; minutes: number; plan?: [string, number][]; noMilitary?: boolean; setup?: (g: Game) => void; at?: { sec: number; fn: (g: Game) => void }[] }

const scenarios: Scenario[] = [
  { id: 'A', title: 'Balanced opening (default AI build order)', question: 'Is the start stable, and when do Code, Hash and army come online?', minutes: 12 },
  { id: 'B', title: 'Greedy mining (3 rigs before Compute Node / 2nd Compiler)', question: 'Does early mining pay back, and what does the brownout cost?', minutes: 12,
    plan: [['compiler', 1], ['rig', 1], ['rig', 2], ['rig', 3], ['bank', 1], ['grid', 1], ['node', 1], ['compiler', 2], ['bank', 2], ['compiler', 3], ['node', 2], ['bank', 3]] },
  { id: 'C', title: 'Code-first turtle (3 Compilers + 2 Towers before any Rig)', question: 'What does delaying mining cost in Hash and army timing?', minutes: 12,
    plan: [['compiler', 1], ['compiler', 2], ['bank', 1], ['compiler', 3], ['node', 1], ['grid', 1], ['bank', 2], ['rig', 1], ['rig', 2], ['bank', 3], ['rig', 3]] },
  { id: 'D', title: 'Army upkeep shock (+14 Bulwarks at 6:00)', question: 'Does a large army starve the economy, and does it recover without a death spiral?', minutes: 12,
    at: [{ sec: 360, fn: g => { const w = g.world; const c = w.coreOf(1)!; for (let i = 0; i < 14; i++) w.spawnUnit('bulwark', 1, c.x + 4 + (i % 5) * 0.8, c.y - 5 - Math.floor(i / 5) * 0.8); } }] },
  { id: 'E', title: 'Starvation recovery (20 Runners, 0 Code, one staffed Compiler)', question: 'Can a starving population recover through rations, crashes-as-suspension and compilers?', minutes: 8,
    setup: g => { const w = g.world; const c = w.coreOf(1)!; for (let i = 0; i < 16; i++) w.spawnUnit('runner', 1, c.x + 4 + (i % 4) * 0.7, c.y - 4 - Math.floor(i / 4) * 0.7);
      const b = w.spawnBuilding('compiler', 1, 12, 49, false); b.hp = b.maxHp; completeBuilding(w, b); const bank = w.spawnBuilding('bank', 1, 12, 46, false); bank.hp = bank.maxHp; completeBuilding(w, bank); w.spawnBuilding('bank', 1, 15, 46, true);
      w.players[1].code = 0; w.players[1].data = 200; } },
];

function run(sc: Scenario) {
  const g = new Game({ seed: 4242, players: [{ name: 'Econ', ai: true }, { name: 'Passive', ai: false }] });
  const ai = g.ais[0];
  g.ais[0] = new AIController(1, 'normal', { ...ai.s, noAttack: true, plan: sc.plan, noMilitary: sc.noMilitary });
  sc.setup?.(g);
  const w = g.world; const p = w.players[1];
  const rows: any[] = [];
  const events: string[] = [];
  const firsts: Record<string, number> = {};
  let minStab = 100;
  for (let t = 0; t <= sc.minutes * 60 * B.tickRate; t++) {
    for (const a of sc.at ?? []) if (t === a.sec * B.tickRate) a.fn(g);
    if (t > 0) g.step();
    minStab = Math.min(minStab, p.stability);
    for (const e of w.entities) if (e.owner === 1 && e.kind === 'building' && e.built && firsts[e.type] === undefined) firsts[e.type] = w.tick;
    if (t % (30 * B.tickRate) === 0) {
      let upkeep = 0; for (const e of w.entities) if (e.kind === 'unit' && e.owner === 1 && !e.suspended && !e.forkOf) upkeep += B.units[e.type].upkeep;
      const caps = w.caps(1);
      rows.push({
        t: `${Math.floor(w.tick / 600)}:${String(Math.floor(w.tick / 10) % 60).padStart(2, '0')}`,
        data: Math.round(p.data), code: Math.round(p.code), hash: Math.round(p.hash),
        codeIn: +(codeIncomeRate(w, 1) * 60).toFixed(0), codeOut: +(upkeep * B.economy.rations[p.ration].mult / B.economy.upkeepCycleSec * 60).toFixed(0),
        stab: Math.round(p.stability), ration: p.ration[0].toUpperCase(),
        compute: `${w.computeDemand(1)}/${caps.compute}`, mem: `${w.memUsed(1)}/${caps.memory}`,
        runners: w.entities.filter(e => e.owner === 1 && e.type === 'runner').length,
        army: w.entities.filter(e => e.owner === 1 && e.kind === 'unit' && e.type !== 'runner').length,
        suspended: w.entities.filter(e => e.owner === 1 && e.suspended).length,
      });
    }
  }
  for (const a of p.alerts) events.push(a.kind);
  return { sc, rows, stats: { ...p.stats }, firsts, minStab: Math.round(minStab) };
}

const results = scenarios.map(run);
const fmtT = (tick?: number) => tick === undefined ? '—' : `${Math.floor(tick / 600)}:${String(Math.floor(tick / 10) % 60).padStart(2, '0')}`;
let md = `# Economy simulation results\n\nGenerated by \`npm run econ\` (tools/econ_sim.ts) on ${new Date().toISOString().slice(0, 10)} with balance v${B.version}.\n` +
  `Each scenario runs the real simulation headless with a scripted economic personality (the Rival AI's economy code with attacks disabled) against a passive opponent. ` +
  `**These numbers are balance evidence about flows and stability. They say nothing about whether the game is fun.**\n\n` +
  `Columns: codeIn/codeOut = Code per minute produced (Compilers + Core trickle) vs eaten (upkeep × ration). Ration S/L/U = Standard/Lean/sUrplus. Compute = demand/supply. Susp = suspended (crashed or parked) programs.\n\n`;
for (const r of results) {
  md += `## ${r.sc.id}. ${r.sc.title}\n\n*Question:* ${r.sc.question}\n\n`;
  md += `First completions — Compiler ${fmtT(r.firsts.compiler)}, Rig ${fmtT(r.firsts.rig)}, Compute Node ${fmtT(r.firsts.node)}, Training Grid ${fmtT(r.firsts.grid)}, Tower ${fmtT(r.firsts.tower)}.  \n`;
  md += `Totals — Data harvested ${Math.round(r.stats.dataHarvested)}, Code produced ${Math.round(r.stats.codeProduced)}, Code eaten ${Math.round(r.stats.codeConsumed)}, Hash mined ${Math.round(r.stats.hashMined)}, programs trained ${r.stats.unitsTrained}, crashes ${r.stats.crashes}, lowest Stability ${r.minStab}.\n\n`;
  md += `| time | Data | Code | Hash | codeIn/min | codeOut/min | Stab | Ration | Compute | Memory | Runners | Army | Susp |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n`;
  for (const x of r.rows.filter((_: any, i: number) => i % 2 === 0 || i === r.rows.length - 1)) md += `| ${x.t} | ${x.data} | ${x.code} | ${x.hash} | ${x.codeIn} | ${x.codeOut} | ${x.stab} | ${x.ration} | ${x.compute} | ${x.mem} | ${x.runners} | ${x.army} | ${x.suspended} |\n`;
  md += '\n';
}
mkdirSync('docs', { recursive: true });
writeFileSync('docs/ECON_SIM_RESULTS.md', md);
writeFileSync('docs/econ_sim.json', JSON.stringify(results.map(r => ({ id: r.sc.id, title: r.sc.title, stats: r.stats, firsts: r.firsts, minStab: r.minStab, rows: r.rows })), null, 1));
for (const r of results) console.log(`${r.sc.id}: hash ${Math.round(r.stats.hashMined)} codeP ${Math.round(r.stats.codeProduced)} trained ${r.stats.unitsTrained} crashes ${r.stats.crashes} minStab ${r.minStab} grid@${fmtT(r.firsts.grid)} rig@${fmtT(r.firsts.rig)}`);
