// Mirror-match fairness experiment (plan from Kernel_Keep_Master_v0.2 docs/04). Two identical rule-based AIs
// on the point-symmetric map.
//  Part A — id-order check: the same game with P1's or P2's start entities inserted first (who gets lower ids).
//           After the v0.2 fixes, the outcome must not depend on insertion order.
//  Part B — paired win-rate: the AIs contain no randomness and the map is fixed, so the seed alone changes nothing.
//           Each seed therefore draws a pair of AI decision phases (a, b) in 0..9, and the game is played twice:
//           phases (a, b) and the swapped (b, a). A fair game should give P1 ≈ 50% over all games.
// Usage: npx tsx tools/fairness.ts [seeds=12] [minutes=25]  → docs/FAIRNESS_RESULTS.md + docs/fairness.json
import { writeFileSync } from 'node:fs';
import { Game, stateHash } from '../src/sim/game.ts';
import { B } from '../src/sim/types.ts';
import { Rng } from '../src/sim/rng.ts';

const SEEDS = Number(process.argv[2] ?? 12), MINUTES = Number(process.argv[3] ?? 25);
interface Row { part: 'A' | 'B'; seed: number; setupOrder: string; phases: [number, number]; winner: number; durationTicks: number; firstContactTick: number; p1Lost: number; p2Lost: number; p1Data: number; p2Data: number; finalHash: string }
const rows: Row[] = [];

function play(part: Row['part'], seed: number, setupOrder: 'p1first' | 'p2first', phases: [number, number]): Row {
  const g = new Game({ seed, setupOrder, aiPhase: { 1: phases[0], 2: phases[1] }, players: [{ name: 'A', ai: true }, { name: 'B', ai: true }] });
  const w = g.world; let contact = -1;
  for (let t = 0; t < MINUTES * 600 && !w.winner; t++) {
    g.step();
    if (contact < 0 && w.events.some(e => e.t === 'shot' && e.owner !== 0 && (w.byId.get(e.to)?.owner ?? 0) !== e.owner)) contact = w.tick;
  }
  const r: Row = { part, seed, setupOrder, phases, winner: w.winner, durationTicks: w.tick, firstContactTick: contact, p1Lost: w.players[1].stats.unitsLost, p2Lost: w.players[2].stats.unitsLost, p1Data: Math.round(w.players[1].stats.dataHarvested), p2Data: Math.round(w.players[2].stats.dataHarvested), finalHash: stateHash(w) };
  rows.push(r); console.log(JSON.stringify(r)); return r;
}

// Part A
const idPairs: [number, number][] = [[3, 6], [6, 3], [0, 0]];
for (const ph of idPairs) for (const so of ['p1first', 'p2first'] as const) play('A', 1, so, ph);
// Part B
for (let seed = 1; seed <= SEEDS; seed++) {
  const rng = new Rng(seed * 7919); const r = () => rng.next();
  const a = Math.floor(r() * 10); let b = Math.floor(r() * 10); if (b === a) b = (a + 5) % 10;
  play('B', seed, 'p1first', [a, b]); play('B', seed, 'p1first', [b, a]);
}

const fmt = (t: number) => `${Math.floor(t / 600)}:${String(Math.floor(t / 10) % 60).padStart(2, '0')}`;
const A = rows.filter(r => r.part === 'A'), Bs = rows.filter(r => r.part === 'B');
const idOk = idPairs.every(ph => { const [x, y] = A.filter(r => r.phases[0] === ph[0] && r.phases[1] === ph[1]); return x.winner === y.winner && x.durationTicks === y.durationTicks && x.p1Data === y.p1Data && x.p2Data === y.p2Data; });
const p1 = Bs.filter(r => r.winner === 1).length, p2 = Bs.filter(r => r.winner === 2).length, und = Bs.filter(r => !r.winner).length;
// two-sided exact binomial test on decided games, H0: p = 0.5
const n = p1 + p2, k = Math.min(p1, p2);
let tail = 0; for (let i = 0; i <= k; i++) { let c = 1; for (let j = 0; j < i; j++) c = c * (n - j) / (j + 1); tail += c / 2 ** n; }
const pval = Math.min(1, 2 * tail);
const d = Bs.filter(r => r.winner).map(r => r.durationTicks).sort((x, y) => x - y);
const dataRatio = Bs.reduce((s, r) => s + r.p1Data, 0) / Math.max(1, Bs.reduce((s, r) => s + r.p2Data, 0));

let md = `# Mirror-match fairness experiment\n\nGenerated by \`npx tsx tools/fairness.ts ${SEEDS} ${MINUTES}\` on ${new Date().toISOString().slice(0, 10)} (balance v${B.version}). Two identical rule-based AIs play on the point-symmetric *Meridian Divide*, with a ${MINUTES}-minute cap. Status: **Tested** (numbers below were produced by this run).\n\n`;
md += `## A. Entity-id order (who gets the lower ids)\n\nThe same game is played with P1's start entities inserted first, then with P2's. Result: **${idOk ? 'identical outcome, length and Data totals in every pair — insertion order no longer decides the game' : 'OUTCOMES DIFFER — insertion order still matters'}**.\n\n| AI phases (P1,P2) | Setup order | Winner | Length | P1 Data | P2 Data |\n|---|---|---|---|---|---|\n`;
for (const r of A) md += `| ${r.phases.join(',')} | ${r.setupOrder} | ${r.winner || '—'} | ${fmt(r.durationTicks)} | ${r.p1Data} | ${r.p2Data} |\n`;
md += `\n## B. Paired win rate\n\nThe AIs use no randomness, so the seed alone does not change the game. Each seed draws AI decision phases (a, b). Every pair is played twice, as (a, b) and as the swapped (b, a).\n\n| Games | P1 wins | P2 wins | Undecided | Two-sided binomial p (decided games) | Median length | Σ P1 Data / Σ P2 Data |\n|---|---|---|---|---|---|---|\n| ${Bs.length} | ${p1} | ${p2} | ${und} | ${pval.toFixed(3)} | ${d.length ? fmt(d[Math.floor(d.length / 2)]) : '—'} | ${dataRatio.toFixed(2)} |\n\n`;
md += `| seed | phases | winner | length | first contact | P1 lost | P2 lost | P1 Data | P2 Data | final hash |\n|---|---|---|---|---|---|---|---|---|---|\n`;
for (const r of Bs) md += `| ${r.seed} | ${r.phases.join(',')} | ${r.winner || '—'} | ${fmt(r.durationTicks)} | ${r.firstContactTick >= 0 ? fmt(r.firstContactTick) : '—'} | ${r.p1Lost} | ${r.p2Lost} | ${r.p1Data} | ${r.p2Data} | ${r.finalHash} |\n`;
md += `\n## What was fixed, and the result

The first run of this experiment, before any fixes, found that the player whose start entities had the **higher** ids won 10/10 in every configuration, whatever the seed. A later run (0.2) still found P1 winning 18 of 24. Each fix below was found by bisecting with \`tools/mirror_probe.ts\`, which runs two identical AIs and reports the first tick where the point-mirrored states differ.

**0.2 fixes:**
1. **Separation** is Jacobi-style: every push is computed from start-of-step positions, then applied.
2. **Simultaneous damage** (\`applyHits\`).
3. **Mirrored tie-breaks** for player 2 in:
   - build placement;
   - spawn tiles;
   - A* neighbour expansion;
   - the \`nearestPassable\` ring scan.
4. **Arrival epsilon** for waypoints.

**0.3.1 fixes:**
5. **Fixed-point positions.** Unit positions snap each tick to a 1/4096-tile lattice, symmetric about the map centre and offset by half a step, so a position is never an exact integer and \`Math.floor\` mirrors exactly. Before this, floats let 64 − x round differently from x, and crowding at wells amplified that 1e-13 noise about tenfold per tick.
6. **Deferred movement.** Every program decides from the same start-of-tick world, and moves are applied after the loop. Before this, the lower id moved first and the other side reacted to its new position.
7. **Mirror-consistent staggering.** Auto-acquire scans are staggered by each player's own spawn sequence (\`Entity.seq\`), not the global id. The global id put mirrored twins on different ticks.
8. **Mirrored AI offsets.** Formation slots, the Fork clone offset and the AI's rally and scout offsets are laid out in each player's own frame.
9. **Ring-scan epsilon.** Float noise can no longer break an exact distance tie.

**Result:**
- With equal AI phases, the two sides stay **exactly mirror-identical (to 1e-9) for 20,000 ticks, over 33 minutes**, and the match is a draw.
- In section B, every swapped pair produces the opposite winner: **11–11, p = 1.00, Data ratio 1.00**.
- Which side wins is now decided by which AI's decision cycle falls earlier relative to the other's, not by the side it plays.
- Paired lengths still differ by a few seconds. That is a small leftover asymmetry, most likely the per-tick pathfinding budget, which is spent in id order. It does not change any winner here.
`;
writeFileSync('docs/FAIRNESS_RESULTS.md', md);
writeFileSync('docs/fairness.json', JSON.stringify(rows, null, 1));
